CREATE DATABASE ECOMMERCE_APPLICATION

CREATE TABLE CUSTOMERS
(
CUSTOMER_ID INT  IDENTITY (001,1)PRIMARY KEY,
[NAME] NVARCHAR(30),
EMAIL NVARCHAR(30),
PASSWORD NVARCHAR(30)
)

CREATE TABLE PRODUCTS
(
PRODUCT_ID INT IDENTITY (00001,1) PRIMARY KEY,
[NAME] NVARCHAR(30),
PRICE FLOAT NOT NULL,
[DESCRIPTION] NVARCHAR(255),
STOCKQUANTITY INT NOT NULL
)

CREATE TABLE CART
(
CART_ID INT IDENTITY(1,1) PRIMARY KEY,
CUSTOMER_ID INT,
PRODUCT_ID INT,
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
QUANTITY INT
)

CREATE TABLE ORDERS
(
ORDER_ID INT IDENTITY (01,1) PRIMARY KEY,
CUSTOMER_ID INT,
ORDER_DATE DATE,
TOTAL_PRICE FLOAT,
SHIPPING_ADDRESS NVARCHAR(255)
FOREIGN KEY (CUSTOMER_ID) REFERENCES CUSTOMERS(CUSTOMER_ID),
)

CREATE TABLE ORDER_ITEMS
(
ORDER_ITEM_ID INT IDENTITY(1,1) PRIMARY KEY,
ORDER_ID INT,
PRODUCT_ID INT,
QUANTITY INT,
FOREIGN KEY (ORDER_ID) REFERENCES ORDERS(ORDER_ID),
FOREIGN KEY (PRODUCT_ID) REFERENCES PRODUCTS(PRODUCT_ID),
)