select * from CUSTOMERS

select * from PRODUCTS


INSERT INTO CART (CUSTOMER_ID, PRODUCT_ID, QUANTITY) VALUES (1, 1, 2);  
INSERT INTO CART (CUSTOMER_ID, PRODUCT_ID, QUANTITY) VALUES (1, 3, 1);  
INSERT INTO CART (CUSTOMER_ID, PRODUCT_ID, QUANTITY) VALUES (2, 2, 1);  
INSERT INTO CART (CUSTOMER_ID, PRODUCT_ID, QUANTITY) VALUES (3, 3, 3);  

INSERT INTO ORDERS (CUSTOMER_ID, ORDER_DATE, TOTAL_PRICE, SHIPPING_ADDRESS)
VALUES
(01, '2025-06-17', 89999.48, '123 Elm Street, Chennai'),
(02, '2025-06-16', 24999.50, '456 Oak Avenue, Bangalore'),
(03, '2025-06-15', 8999.97, '789 Pine Road, Hyderabad');

INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY) VALUES (1, 1, 1);  
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY) VALUES (1, 2, 1);  
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY) VALUES (2, 2, 1);  
INSERT INTO ORDER_ITEMS (ORDER_ID, PRODUCT_ID, QUANTITY) VALUES (3, 3, 3);  

